ALTER TABLE "products" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "products_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1000 CACHE 1);--> statement-breakpoint
ALTER TABLE "products" ALTER COLUMN "description" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "barcode" text NOT NULL;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "quantity" text;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "price_observed_on" date NOT NULL;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "nutriscore_grade" text;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "nova_group" integer;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "labels" jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "allergens" jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "ingredients_text" text;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "nutriments" jsonb;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "nutrition_per" text;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "scan_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_barcode_unique" UNIQUE("barcode");