/**
 * Integration coverage for the guest-cart merge against the real catalog.
 * Needs DATABASE_URL; run with `npm run test:db`.
 *
 * Supabase Auth is not involved: the merge takes a user id, so a synthetic
 * UUID exercises the same path a real session would. Every test cleans up
 * after itself and no catalog row is modified.
 *
 * Fixtures are read from the live catalog rather than hard-coded: product ids
 * are generated by the import, so any two real products will do.
 */
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { after, before, test } from "node:test";
import { asc, eq } from "drizzle-orm";
import { MAX_PER_LINE, sumCarts, type CartLine } from "../lib/cart";
import { reconcileLines, readUserCart, writeUserCart } from "../lib/cart-store";
import { db } from "../lib/db";
import { cartItems, products } from "../lib/db/schema";

/** An id the identity column will never reach in this catalog's lifetime. */
const GONE = 2_000_000_000;

let A = 0;
let B = 0;

before(async () => {
  const rows = await db.select({ id: products.id }).from(products).orderBy(asc(products.id)).limit(2);
  assert.equal(rows.length, 2, "the catalog needs at least two products — run npm run db:seed");
  [A, B] = rows.map((r) => r.id);
});

const users: string[] = [];
function newUser(): string {
  const id = randomUUID();
  users.push(id);
  return id;
}

/** The merge, minus the cookie I/O: sum, then drop stale lines and cap. */
async function merge(guest: CartLine[], user: CartLine[]): Promise<CartLine[]> {
  return reconcileLines(sumCarts(guest, user));
}

after(async () => {
  for (const id of users) await db.delete(cartItems).where(eq(cartItems.userId, id));
  process.exit(0);
});

test("a user cart round-trips through the database", async () => {
  const user = newUser();
  await writeUserCart(user, [
    { i: A, q: 2 },
    { i: B, q: 1 },
  ]);
  const read = await readUserCart(user);
  assert.deepEqual(
    [...read].sort((x, y) => x.i - y.i),
    [
      { i: A, q: 2 },
      { i: B, q: 1 },
    ].sort((x, y) => x.i - y.i),
  );
});

test("writing replaces the previous cart rather than appending", async () => {
  const user = newUser();
  await writeUserCart(user, [{ i: A, q: 2 }]);
  await writeUserCart(user, [{ i: B, q: 1 }]);
  assert.deepEqual(await readUserCart(user), [{ i: B, q: 1 }]);
});

test("writing an empty cart clears it", async () => {
  const user = newUser();
  await writeUserCart(user, [{ i: A, q: 2 }]);
  await writeUserCart(user, []);
  assert.deepEqual(await readUserCart(user), []);
});

test("two users' carts do not interfere", async () => {
  const a = newUser();
  const b = newUser();
  await writeUserCart(a, [{ i: A, q: 2 }]);
  await writeUserCart(b, [{ i: B, q: 1 }]);
  assert.deepEqual(await readUserCart(a), [{ i: A, q: 2 }]);
  assert.deepEqual(await readUserCart(b), [{ i: B, q: 1 }]);
});

test("merge SUMS duplicate products", async () => {
  assert.deepEqual(await merge([{ i: A, q: 2 }], [{ i: A, q: 3 }]), [{ i: A, q: 5 }]);
});

test("merge caps the summed quantity at the per-line limit", async () => {
  const merged = await merge([{ i: A, q: 9 }], [{ i: A, q: 8 }]);
  assert.deepEqual(merged, [{ i: A, q: MAX_PER_LINE }]);
});

test("merge drops products that have left the catalog", async () => {
  assert.deepEqual(await merge([{ i: GONE, q: 3 }], [{ i: A, q: 1 }]), [{ i: A, q: 1 }]);
});

test("merge keeps guest lines first", async () => {
  assert.deepEqual(await merge([{ i: B, q: 1 }], [{ i: A, q: 1 }]), [
    { i: B, q: 1 },
    { i: A, q: 1 },
  ]);
});

test("merge of two empty carts is empty", async () => {
  assert.deepEqual(await merge([], []), []);
});

test("merge preserves an account cart when the guest cart is empty", async () => {
  assert.deepEqual(await merge([], [{ i: A, q: 4 }]), [{ i: A, q: 4 }]);
});

test("a merged cart persists for the next session", async () => {
  const user = newUser();
  await writeUserCart(user, [{ i: A, q: 3 }]);
  const merged = await merge([{ i: A, q: 2 }], await readUserCart(user));
  await writeUserCart(user, merged);
  assert.deepEqual(await readUserCart(user), [{ i: A, q: 5 }]);
});
